# Generated by Django 3.2.6 on 2021-09-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioModel',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('senha', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Senha')),
                ('superusuario', models.BooleanField(default=False, verbose_name='Super usuário')),
                ('horario', models.CharField(max_length=50, verbose_name='Hora de trabalho')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departamentomodel')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoHorarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(default='limpo', max_length=30, verbose_name='Status')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Saida')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionariomodel')),
            ],
        ),
    ]
